name: CI

on:
  push:
    branches: [ main, websocket ]
  pull_request:
    branches: [ main, websocket ]

env:
  CARGO_TERM_COLOR: always

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
    
    - name: Cache Cargo registry
      uses: actions/cache@v3
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Cache Cargo index
      uses: actions/cache@v3
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Cache Cargo build
      uses: actions/cache@v3
      with:
        path: target
        key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Run e2e tests
      run: |
        npm install -g @iflow-ai/iflow-cli@latest
        mkdir -p ~/.iflow
        cat > ~/.iflow/settings.json <<'EOF'
        ${{ secrets.IFLOW_SETTINGS_JSON }}
        EOF
        cargo test --test e2e_tests -- --nocapture
        cargo run --example websocket_client