name: Rust Coverage

on:
  workflow_dispatch:
  pull_request:
    paths: ['**/*.rs', 'Cargo.toml', 'Cargo.lock', 'tests/**', 'examples/**']

jobs:
  coverage:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: llvm-tools-preview

      - name: Install cargo-llvm-cov
        run: cargo install cargo-llvm-cov --locked

      - name: Generate coverage report
        run: |
          npx -v
          npm install -g @iflow-ai/iflow-cli@latest
          mkdir -p ~/.iflow
          cat > ~/.iflow/settings.json <<'EOF'
          {
              "selectedAuthType": "iflow",
              "apiKey": "${{ secrets.COVERAGE_IFLOW_API_KEY }}",
              "baseUrl": "https://apis.iflow.cn/v1",
              "modelName": "Qwen3-Coder",
              "searchApiKey": "${{ secrets.COVERAGE_IFLOW_API_KEY }}"
          }
          EOF
          RUST_LOG=debug cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info -- --nocapture
        env:
          RUSTFLAGS: "-C instrument-coverage"
          RUST_LOG: debug

      - name: Upload to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./lcov.info
          fail_ci_if_error: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
