name: CI (E2E-Windows)

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  e2e-tests-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@master
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Run e2e tests
      shell: pwsh
      run: |
        npx -v
        npm install -g @iflow-ai/iflow-cli@latest
        if (!(Test-Path "$env:USERPROFILE\.iflow")) { New-Item -ItemType Directory -Path "$env:USERPROFILE\.iflow" }
        Set-Content -Path "$env:USERPROFILE\.iflow\settings.json" -Value "${{ secrets.IFLOW_SETTINGS_JSON }}"
        $env:RUST_LOG="debug"
        cargo run --example websocket_client
